title: Dokumen Prodi Sarjana Terapan Teknik Informatika
description: Data, dokumen, kelengkapan untuk akreditasi dan audit.
show_downloads: true
google_analytics:
theme: jekyll-theme-dinky

remote_theme: pages-themes/dinky@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one